CREATE TABLE tABLE_DEFAULT(
   LOGIN_ID VARCHAR2(20) CONSTRAINT TBLDF_LGNID_PK PRIMARY KEY,
   LOGIN_PWD VARCHAR2(20) DEFAULT '1234',
   TEL VARCHAR2(20));
-- ORA-01031: 권한이 불충분합니다

CREATE TABLE tABLE_DEFAULT(
   LOGIN_ID VARCHAR2(20) CONSTRAINT TBLDF_LGNID_PK PRIMARY KEY,
   LOGIN_PWD VARCHAR2(20) DEFAULT '1234',
   TEL VARCHAR2(20));
   
INSERT INTO TABLE_DEFAULT(LOGIN_ID, LOGIN_PWD)
VALUES('TEST_ID','TEST_ID');
--ORA-01950: 테이블스페이스 'USERS'에 대한 권한이 없습니다.